debug: false
server:
  port: 8080
spring:
  ai:
    vectorstore:
      milvus:
        host: localhost
        port: 19530
        databaseName: default
        collectionName: documents
        embeddingDimension: 768
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true
    ollama:
      embedding:
        options:
          model: nomic-embed-text

milvus:
  host: localhost
  port: 19530
  database: default
  collection:
    dimension: 768


ollama:
  host: http://localhost
  port: 11434
  model: nomic-embed-text

file:
  upload-dir: uploads